spring:
  # PostgreSQL 데이터베이스 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/mydiet
    username: mydiet
    password: mydiet123
    driver-class-name: org.postgresql.Driver
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
  # 서버 설정
  web:
    resources:
      static-locations: classpath:/static/
      
# 서버 설정 (중복 제거)
server:
  port: 8080
  servlet:
    context-path: /
    
# Claude API 설정
claude:
  api:
    key: your_claude_api_key_here
    
# 로깅 설정
logging:
  level:
    com.mydiet: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG