-- 시퀀스 생성 (이미 존재하면 에러 발생하지만 무시됨)
CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1;

-- 관리자 계정 생성 (단순 INSERT, 중복시 에러 발생하지만 무시됨)
INSERT INTO MYDIET_USER (USER_ID, EMAIL, PASSWORD, NICKNAME, WEIGHT_GOAL, TARGET_CALORIES, EMOTION_MODE, USER_ROLE, CREATED_AT)
VALUES (USER_SEQ.NEXTVAL, 'admin@mydiet.com', 'password', '관리자', 70.0, 2000.0, '무자비', 'ADMIN', SYSDATE);

-- 테스트 사용자
INSERT INTO MYDIET_USER (USER_ID, EMAIL, PASSWORD, NICKNAME, WEIGHT_GOAL, TARGET_CALORIES, EMOTION_MODE, USER_ROLE, CREATED_AT)
VALUES (USER_SEQ.NEXTVAL, 'user1@test.com', 'password', '다이어터1', 60.0, 1800.0, '츤데레', 'USER', SYSDATE);
